### ISSUE TITLE
What's the best way to include this in scoper.inc.php?

### ISSUE THREAD

**Issue by AdamWills** [sniccowp/php-scoper-wordpress-excludes#3]
A readme with an example would be very helpful!

**Comment by calvinalkan** [comment]
Hey @AdamWills 

There is not much to it. Json_decode the file contents directly in scoper.inc.php

Have a look at how Google did it in their web stories plugin:

https://github.com/GoogleForCreators/web-stories-wp/blob/main/scoper.inc.php#L13

There are many different ways tho.
