### ISSUE TITLE
Package not auto-updating

### ISSUE THREAD

**Issue by szepeviktor** [sniccowp/php-scoper-wordpress-excludes#5]
`Last update: 2022-05-13 12:10:18 UTC`
https://packagist.org/packages/sniccowp/php-scoper-wordpress-excludes

**Comment by calvinalkan** [comment]
This looks like something went wrong on packagists site there. This should be updated through normal GitHub webhooks to packagist. 

Manualy updated a new release now in packagist. 
Ill keep an eye on it to see if it happens again.

**Comment by mundschenk-at** [comment]
Looks like it has happened again with 6.2.0.

**Comment by calvinalkan** [comment]
It looks like 6.2 got tagged correctly.

https://github.com/snicco/php-scoper-wordpress-excludes/commit/a6f49e86ca8468d07efd6ca2947af9636436c82a

Am I missing something?

**Comment by mundschenk-at** [comment]
It's not on Packagist.

**Comment by szepeviktor** [comment]
![image](https://user-images.githubusercontent.com/952007/229303762-674b5de5-18e7-42b5-b8e8-5fd6dfa8a1ff.png)

**Comment by calvinalkan** [comment]
Weird. Manually synced it now. Not sure there is much more we can do from our end.

**Comment by szepeviktor** [comment]
In "Webhooks" you can control settings and see the log.

![image](https://user-images.githubusercontent.com/952007/229306542-b75f2397-0ca3-4c32-b11b-73b0ebdfd068.png)
