### ISSUE TITLE
Feature Request: Add WP_CLI classes/functions

### ISSUE THREAD

**Issue by defunctl** [sniccowp/php-scoper-wordpress-excludes#7]
Generally we don't want these scoped either when making custom commands etc...

**Comment by calvinalkan** [comment]
This is a good question. 

There are https://github.com/php-stubs/wp-cli-stubs

Which could be used. 

Wondering if these should be in this package tho.

You could also use https://github.com/snicco/php-scoper-excludes
directly to generate the stubs.

**Comment by calvinalkan** [comment]
I checked how we do that in Fortress, we never had an issue with this:

    'exclude-classes' => \array_merge($wordpress_classes, [WP_CLI::class]),

    'exclude-functions' => $wordpress_functions,

    'exclude-constants' => \array_merge(
        [WP_CLI::class],
        ['/^SYMFONY\_[\p{L}_]+$/'],
        $wordpress_constants
    ),

    'exclude-namespaces' => [
        'Snicco\Enterprise',
        'Symfony\Polyfill',
        WP_CLI::class, // We don't have the WP_CLI package as a composer dependency, it is expected to be installed on the client site.
    ],

**Comment by calvinalkan** [comment]
You can whitelist the namespace.

**Comment by defunctl** [comment]
I was also manually excluding it (since it is include in composer in our case), which is totally fine. I wasn't aware of the other stubs either.

The example is helpful though because I realize I wasn't excluding any constants. 

Feel free to close if you want :)
