### ISSUE TITLE
Add `DISABLE_WP_CRON` 

### ISSUE THREAD

**Issue by saas786** [sniccowp/php-scoper-wordpress-excludes#8]
Ref: https://github.com/WordPress/WordPress/blob/bbe67a01472b10a83181b126d5edadf4f6caff0c/wp-includes/cron.php#L997

**Comment by calvinalkan** [comment]
There's not much we can do if constants are missing in upstream stubs packages.

https://github.com/php-stubs/wordpress-globals

If a particular one is missing, you could just merge the constants here in the php scoper config.

**Comment by calvinalkan** [comment]
See: 

https://github.com/snicco/php-scoper-wordpress-excludes/issues/7#issuecomment-1645797061
