### ISSUE TITLE
Release 6.5 excludes

### ISSUE THREAD

**Issue by swissspidy** [sniccowp/php-scoper-wordpress-excludes#9]
The automatic release workflow is currently disabled because it hasn't been active for 2 months. Need to re-enable it to trigger the 6.5 update

**Comment by calvinalkan** [comment]
Damn, that's annoying. Will look into adding a cron action that re-enables it automatically if that's possible.

That said, upstream is stuck at 6.4.3

https://github.com/php-stubs/wordpress-stubs/releases

**Comment by swissspidy** [comment]
Upstream has now been updated 👍
